common/urls.py
from django.urls import path
from . import views
app_name = "common"
urlpatterns = [
   
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('customerregister',views.customerregister,name='customerregister'),
    path('customerlogin',views.customerlogin,name='customerlogin'),
    path('eadminregister',views.eadminregister,name='eadminregister'),
    path('eadminlogin',views.eadminlogin,name='eadminlogin'),

]

customer/urls.py
from django.urls import path
from . import views
app_name = "customer"
urlpatterns = [
   
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('productdetails/<int:pid>',views.productdetails,name='productdetails'),
    path('logout',views.logout,name='logout'),
  

]

eadmin/urls.py
from django.urls import path
from . import views
app_name = "eadmin"
urlpatterns = [
   
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('register',views.register,name='register'),
    path('viewcustomer',views.viewcustomer,name='viewcustomer'),
    path('managepurchase',views.managepurchase,name='managepurchase'),
    path('manageproduct',views.manageproduct,name='manageproduct'),
    path('logout',views.logout,name='logout'),
    path('delete/<int:id>',views.delete_purchase,name='delete_purchase'),
   
]

mobile/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include('common.urls')),
    path('customer/',include('customer.urls')),
    path('eadmin/',include('eadmin.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length = 30)
    contact = models.BigIntegerField()
    email = models.CharField(max_length = 30)
    username = models.CharField(max_length = 25)
    password = models.CharField(max_length = 20)
    confirm = models.CharField(max_length = 20)




class Eadmin(models.Model):
    name = models.CharField(max_length = 20)
    email = models.CharField(max_length = 30)
    username = models.CharField(max_length = 30)
    password = models.CharField(max_length = 20)

customer/models.py
from django.db import models
from common.models import Customer
from eadmin.models import Product
# Create your models here.


class Purchase(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.CASCADE )
    product = models.ForeignKey(Product, on_delete = models.CASCADE )

eadmin/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length = 30)
    brand = models.CharField(max_length = 20)
    rate = models.FloatField()
    image = models.ImageField(upload_to = 'product/')

common/views.py
from django.shortcuts import render,redirect
from . models import Customer
from .models import Eadmin

# Create your views here.
def master(request):
    return render(request,'client/master.html')
def home(request):
    return render(request,'client/home.html')



def customerregister(request):
    
    if request.method == 'POST':
        c_name = request.POST['fname']
        c_contact = request.POST['phone']
        c_email = request.POST['email']
        c_username = request.POST['username']
        c_password = request.POST['password']
        c_confirm = request.POST['confirm']
        new_customer = Customer(name = c_name, contact = c_contact, email = c_email,
                                username = c_username, password = c_password, confirm = c_confirm)
        new_customer.save()
    return render(request,'client/customerregister.html')



def customerlogin(request):
    msg = ""
    if request.method == 'POST':
        c_username = request.POST['username']
        c_password = request.POST['password']
        try:
             customer = Customer.objects.get(username = c_username, password = c_password)
             request.session['customer'] = customer.id
             return redirect('customer:home')
        except Exception as e:
            print(e)
            msg = "Customer Login Successfully"
    return render(request,'client/customerlogin.html',{'message':msg})


def eadminregister(request):
    if request.method == 'POST':
        e_name = request.POST['name']
        e_email = request.POST['email']
        e_username = request.POST['username']
        e_password = request.POST['password']

        new_eadmin = Eadmin(name = e_name, email = e_email, username = e_username, password = e_password)
        new_eadmin.save()
    return render(request,'client/eadminregister.html')


def eadminlogin(request):
    msg = ""
    if request.method == 'POST':
        e_username = request.POST['username']
        e_password = request.POST['password']
        try:
            eadmin = Eadmin.objects.get(username = e_username, password = e_password)
            request.session['eadmin'] = eadmin.id
            return redirect('eadmin:home')
        except Exception as e:
            print(e)
            msg = "eadmin Login Successfully"
    return render(request,'client/eadminlogin.html',{'message':msg})

customer/views.py
from django.shortcuts import render,redirect
from eadmin.models import Product
from . models import Customer
from . models import Purchase

# Create your views here.
def master(request):
    return render(request,'user/master.html')
def home(request):
    products = Product.objects.all()
    return render(request,'user/home.html',{'product_list':products})
def productdetails(request,pid):
    msg = ""
    product_data = Product.objects.get(id = pid)

    if request.method == 'POST':
        
        product_id = request.POST['pid']
        item_exist = Purchase.objects.filter(product_id = product_id, customer_id = request.session['customer']).exists()
        if not item_exist:

             purchase_item = Purchase(product_id = product_id, customer_id = request.session['customer'])
             purchase_item.save()
             return redirect('eadmin:managepurchase')
        else:
            msg = 'Item alredy purchased'
  
    return render(request,'user/productdetails.html',{'product':product_data,'msg':msg})
def logout(request):
    return render(request,'user/logout.html')

eadmin/views.py
from django.shortcuts import render,redirect
from .models import Product
from common.models import Eadmin
from common.models import Customer
from customer.models import Purchase

# Create your views here.
def master(request):
    return render(request,'shop/master.html')
def home(request):
    return render(request,'shop/home.html')


def register(request):
    msg = ""
    if request.method == 'POST':
        p_name = request.POST['name']
        p_brand = request.POST['brand']
        p_rate = request.POST['rate']
        p_image = request.FILES['file']
        
        new_product = Product(name = p_name, brand = p_brand, rate = p_rate, image = p_image)
        new_product.save()
        msg = "Mobile Phone Registered Successfully"
    return render(request,'shop/register.html',{'message':msg})


def viewcustomer(request):
    
    cust_data = Customer.objects.filter(id = request.session['customer'])
    return render(request,'shop/viewcustomer.html',{'view-list':cust_data})



def managepurchase(request):
    product_data = Purchase.objects.all()
    return render(request,'shop/managepurchase.html',{'purchase_list':product_data})


def manageproduct(request):
    products = Product.objects.all()
    return render(request,'shop/manageproduct.html',{'product_list':products})


def logout(request):
    return render(request,'shop/logout.html')

def delete_purchase(request,id):
    purchase_item = Purchase.objects.get(product = id, customer = request.session['customer'])
 
    purchase_item.delete()
    return redirect('eadmin:managepurchase')

    

common/templates/client/customerlogin.html
{% extends 'client/master.html' %}
{% load static %}

    <title>{% block title %}login{% endblock %}</title>
      {% block link %}
    <link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
   {% endblock %}
  </head>
<body>
 {% block content %}
    <form method="POST">
        {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Username</label>
      <input type="text" class="form-control" id="exampleInputPassword1" name="username">
    </div>

    
   
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
      </div>
   
      <button type="submit" class="btn btn-primary">Login</button><br><br>
    
    </form>
    {{message}}
  {% endblock %}
</body>
</html>

common/templates/client/customerregister.html
{% extends 'client/master.html' %}
{% load static %}

    <title>{% block title %}register{% endblock %}</title>
      {% block link %}
    <link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
   {% endblock %}
  </head>
<body>
 {% block content %}
   <form method="POST">
    {% csrf_token %}
    <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Name</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="fname">
     </div>

    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Contact</label>
      <input type="number" class="form-control" id="exampleInputPassword1" name="phone">
    </div>

    
   
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Email</label>
        <input type="email" class="form-control" id="exampleInputPassword1" name="email">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Username</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="username">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Confirm</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="confirm">
      </div>
      <button type="submit" class="btn btn-primary">Register</button><br><br>
    
    </form>
  {% endblock %}
</body>
</html>

common/templates/client/eadminlogin.html
{% extends 'client/master.html' %}
{% load static %}

    <title>{% block title %}login{% endblock %}</title>
      {% block link %}
    <link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
   {% endblock %}
  </head>
<body>
 {% block content %}
   <form method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Username</label>
      <input type="text" class="form-control" id="exampleInputPassword1" name="username">
    </div>

    
   
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label"> Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
      </div>
      
      <button type="submit" class="btn btn-primary">Login</button><br><br>
    
    </form>
  {% endblock %}
</body>
</html>

common/templates/client/eadminregister.html
{% extends 'client/master.html' %}
{% load static %}

    <title>{% block title %}register{% endblock %}</title>
      {% block link %}
    <link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
   {% endblock %}
  </head>
<body>
 {% block content %}
   <form method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Name</label>
      <input type="text" class="form-control" id="exampleInputPassword1" name="name">
    </div>

    
   
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">email</label>
        <input type="email" class="form-control" id="exampleInputPassword1" name="email">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Username</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="username">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
      </div>
      <button type="submit" class="btn btn-primary">Register</button><br><br>
    
    </form>
  {% endblock %}
</body>
</html>

common/templates/client/home.html
{% extends 'client/master.html' %}
{% load static %}

    <title>{% block title %}home{% endblock %}</title>
      {% block link %}
    <link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
   {% endblock %}
  </head>
<body>
 {% block content %}

   
  {% endblock %}
</body>
</html>

common/templates/client/master.html
{% load static %}

    <title>{% block title %}{% endblock %}</title>
    <link> {% block link %}{% endblock %}</link>
    <link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
</head>
<body>
   <nav class="navbar">
        <div class="logo"><h1>ECOMMERCE</h1></div>
        <ul class="menu">
            <li><a href="{% url 'common:master' %}"></a></li>
            <li><a href="{% url 'common:home' %}">Home</a></li>
            <li><a href="{% url 'common:customerregister' %}">CustomerRegister</a></li>
            <li><a href="{% url 'common:customerlogin' %}">CustomerLogin</a></li>
            <li><a href="{% url 'common:eadminregister' %}">EadminRegister</a></li>
            <li><a href="{% url 'common:eadminlogin' %}">EadminLogin</a></li>
           
       </ul>
    </nav>  
    {% block content %} 
    {% endblock %}

</body>
</html>

customer/templates/user/home.html
{% extends 'user/master.html' %}
{% load static %}
{% block title %}home{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
{% endblock %}
 </head>
<body>
    {% block content %}
        
    </section>

    <h1 class="pheading">View Products</h1>

    <section class="sec">
        <div class="products">
           {% for p in product_list %}
                 <!-- card start -->
                 <div class="card">
                    <div class="img"><img src="{{p.image.url}}"></div>
                    <div class="desc">{{p.name}}</div>
                    <div class="desc">{{p.brand}}</div>
                    <div class="title">Rs{{p.rate}}</div>
                    <div class="box">
                        
                      <a class="btn" href="{% url 'customer:productdetails' p.id  %}">View</a> 
                         
                     </div>    
                 </div>
            {% endfor %}
                 <!-- card end -->
            
             
            
               
                
          
             
            
           
 
           

        </div>

    </section>

   {% endblock %}
    
</body>
</html>

customer/templates/user/logout.html
{% extends 'user/master.html' %}
{% load static %}
{% block title %}Logout{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
{% endblock %}
 </head>
<body>
    {% block content %}
    

   {% endblock %}
    
</body>
</html>

customer/templates/user/master.html
{% load static %}
 
    <title>{% block title %}{% endblock %}</title>
    <link>{% block link %}{% endblock %}</link>
    <link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
 </head>
<body>
    <nav class="navbar">
        <div class="logo"><h1>ECOMMERCE</h1></div>
        <ul class="menu">
            <li><a href="{% url 'customer:master' %}"></a></li>
            <li><a href="{% url 'customer:home' %}">Home</a></li>
            
            
            <li><a href="{% url 'customer:logout' %}">Logout</a></li>
            
            
</ul>
       
    </nav>

    {% block content %}
    {% endblock %}

customer/templates/user/productdetails.html
{% extends 'user/master.html' %}
{% load static %}
{% block title %}Purchase{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
{% endblock %}
 </head>
<body>
    {% block content %}
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{product.image.url}}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
        <form action="" method="POST">
            {% csrf_token %}
            

            <input type="hidden" value="{{product.id}}" name="pid" id="">
              <h5 class="card-title">{{product.name}}</h5>
              <p class="card-text">{{product.brand}}</p>
              <p class="card-text">Rs{{product.rate}}</p>
              <p class="card-text"><small class="text-muted"><button type="submit" class="btn btn-primary">Purchase</button>
              </small></p>
        </form>
        {{msg}}
            </div>
          </div>
        </div>
      </div>
    {% endblock %}
    
</body>
</html>

eadmin/templates/shop/home.html
{% extends 'shop/master.html' %}
{% load static %}
{% block title %}home{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
{% endblock %}
 </head>
<body>
    {% block content %}
    

   {% endblock %}
    
</body>
</html>

eadmin/templates/shop/logout.html
{% extends 'shop/master.html' %}
{% load static %}
{% block title %}logout{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
{% endblock %}
 </head>
<body>
    {% block content %}
    

   {% endblock %}
    
</body>
</html>

eadmin/templates/shop/manageproduct.html
{% extends 'shop/master.html' %}
{% load static %}
{% block title %}manageproduct{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% endblock %}
 </head>
<body>
    {% block content %}

      

          
<table class="table">
            
  <tr>
    <th scope="col">ProductId</th>
    <th scope="col">Name</th>
    <th scope="col">Brand</th>
    <th scope="col">Price</th>
    <th scope="col">Image</th>
    <th scope="col">Delete</th>
    
  </tr>
  {% for  pro in product_list  %}






  <tr>
    <tr>
      <td scope="col">{{pro.id}}</td>
      <td scope="col">{{pro.name}}</td>
      <td scope="col">{{pro.brand}}</td>
      <td scope="col">{{pro.rate}}</td>
      <td scope="col"> <img src="{{pro.image.url}}"></td>
      
     
      
    </tr>
  </tr>
 
  {% endfor %}
</table>
    

   {% endblock %}
    
</body>
</html>

eadmin/templates/shop/managepurchase.html
{% extends 'shop/master.html' %}
{% load static %}
{% block title %}managepurchase{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% endblock %}
 </head>
<body>
    {% block content %}
    

    
    <table class="table">
        
        <tr>
          <th scope="col">Request ID</th>
          <th scope="col">Product </th>
          <th scope="col">Brand</th>
          <th scope="col">Customer</th>
          <th scope="col">Image</th>
          <th scope="col">Rate</th>
          <th scope="col">Viewmore</th>
          <th scope="col">Delete</th>
        </tr>
        {% for  pro in purchase_list %}


    
  
      
     
        <tr>
          <tr>
            <td scope="col">{{pro.customer.id}}</td>
            <td scope="col">{{pro.product.name}}</td>
            <td scope="col">{{pro.product.brand}}</td>
            <td scope="col">{{pro.customer.name}}</td>
            <td scope="col" > <img src="{{pro.product.image.url}}"></td>
            <td scope="col">{{pro.product.rate}}</td>
            <td><button>view more</button></td>
            <td scope="col"><a href="{% url 'eadmin:delete_purchase' pro.product.id %}">Delete</a></td>
          </tr>
        </tr>
       
        {% endfor %}
    </table>




    {% endblock %}
    
</body>
</html>

eadmin/templates/shop/master.html
{% load static %}
 
    <title>{% block title %}{% endblock %}</title>
    <link>{% block link %}{% endblock %}</link>
    <link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
 </head>
<body>
    <nav class="navbar">
        <div class="logo"><h1>ECOMMERCE</h1></div>
        <ul class="menu">
            <li><a href="{% url 'eadmin:master' %}"></a></li>
            <li><a href="{% url 'eadmin:home' %}">Home</a></li>
            <li><a href="{% url 'eadmin:viewcustomer' %}">ViewCustomer</a></li>
            <li><a href="{% url 'eadmin:register' %}">Register</a></li>
            <li><a href="{% url 'eadmin:manageproduct' %}">ManageProducts</a></li>
            <li><a href="{% url 'eadmin:managepurchase' %}">ManagePurchase</a></li>
            <li><a href="{% url 'eadmin:logout' %}">Logout</a></li>
           
          
          
            
            
</ul>
       
    </nav>

    {% block content %}
    {% endblock %}

eadmin/templates/shop/register.html
{% extends 'shop/master.html' %}
{% load static %}
{% block title %}register{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  
{% endblock %}
 </head>
<body>
    {% block content %}
     
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Name</label>
          <input type="text" class="form-control" id="exampleInputPassword1" name="name">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Brand</label>
            <input type="text" class="form-control" id="exampleInputPassword1" name="brand">
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">rate</label>
            <input type="text" class="form-control" id="exampleInputPassword1" name="rate">
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Upload Image</label>
            <input type="file" class="form-control" id="exampleInputPassword1" name="file">
          </div>
    
        
       
          
          <button type="submit" class="btn btn-primary">Register</button><br><br>
        
        </form>
         {{message}}
   {% endblock %}
    
</body>
</html>

eadmin/templates/shop/viewcustomer.html
{% extends 'shop/master.html' %}
{% load static %}
{% block title %}viewcustomer{% endblock %} 
{% block link %}
<link rel="stylesheet"  href="{% static 'css/cushome.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% endblock %}
 </head>
<body>
    {% block content %}
    
    
          
<table class="table">
            
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Contact</th>
      
      
    </tr>
    {% for  p in  view_list  %}
  
  
  
  
  
  
    <tr>
      <tr>
        <td scope="col">{{p.customer.id}}</td>
        <td scope="col">{{p.customer.name}}</td>
        <td scope="col">{{p.customer.email}}</td>
        <td scope="col">{{p.customer.contact}}</td>
        
        
        
      </tr>
    </tr>
   
    {% endfor %}
  </table>

   {% endblock %}
    
</body>
</html>